import Button from '@/components/common/Button';
import Head from 'next/head';

function Home() {
  return (
    <>
      <Head>
        <title>Officener</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button content="Button" variant="blue" isDisabled />
      <Button content="Button" variant="blue" />
      <Button content="Button" variant="grey" />
      <Button content="Button" variant="grey" isDisabled />
      <Button content="Button" variant="secondaryBlue" />
      <Button content="Button" variant="secondaryGrey" />
    </>
  );
}

export default Home;
