import Button from '@/components/common/Button';
import Head from 'next/head';
import Header from '@/components/common/Header';
import RadioBtn from '@/components/common/RadioBtn';

function Home() {
  const onClickHandler = (event: React.MouseEvent<HTMLDivElement>) => {
    event.preventDefault();
    alert('onClick Test');
  };

  // RadioBtn 예시 데이터, API 확인 후 변경 예정
  const arr = ['test1', 'test2', 'test3'];
  return (
    <>
      <Head>
        <title>Officener</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button content="Button" variant="blue" isDisabled />
      <Button content="Button" variant="blue" />
      <Button content="Button" variant="grey" />
      <Button content="Button" variant="grey" isDisabled />
      <Button content="Button" variant="secondaryBlue" />
      <Button content="Button" variant="secondaryGrey" />

      {/* 우측 text가  있는 경우 */}
      <Header title="title" type="text" onClick={onClickHandler} />
      {/* 우측 close 아이콘이 있는 경우 */}
      <Header title="title" type="close" onClick={onClickHandler} />
      {/* title만 있는 경우  */}
      <Header title="title" onClick={onClickHandler} />

      {/* list-데이터 배열, name-데이터 유형) */}
      <RadioBtn list={arr} name="초대 장소" />
    </>
  );
}

export default Home;
